apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: linguistic-stratigraphy
  app.kubernetes.io/managed-by: kustomize
